### ISSUE TITLE
Введення -> Вступ?

### ISSUE THREAD

**Issue by klymenkoo** [reactjs/uk.reactjs.org#117]
Трохи зворотнього зв'язку з Твіттера:
<img width="627" alt="Screen Shot 2019-04-24 at 4 02 06 PM" src="https://user-images.githubusercontent.com/26641473/56690014-741c5c80-66aa-11e9-9a6c-ccc0dd17bd50.png">

Мені здається ми обговорювали заміну `введення` на `вступ`, але все ж таки залишили `введення`. Після пошуку в Гуглі, я дійсно знайшов мало прикладів зі словом введення, вступ є набагато поширеним у використанні.

Які думки?

**Comment by klymenkoo** [comment]
cc: @mihilbabin, @ApolllonDev, @westanvv

**Comment by ochkarik05** [comment]
Порівняв з оригіналом. Виявляється, як "введення" переклали "tutorial".

**Comment by ochkarik05** [comment]
Пропоную "посібник".

**Comment by ochkarik05** [comment]
@klymenkoo https://github.com/reactjs/uk.reactjs.org/pull/118

**Comment by klymenkoo** [comment]
@ochkarik05 Ми цілеспрямовано перекладали це як введення/вступ, аніж посібник, тому що за вмістом цей документ більше схожий на вступ до React, ніж підручник як їм користуватися.

**Comment by ochkarik05** [comment]
Окей, якщо знайдете десь тут вступ, то все норм:
https://e2u.org.ua/s?w=tutorial&dicts=all&highlight=on&filter_lines=on

У будь-якому разі, вирішувати вам. Я його все одно не читатиму.

**Comment by mihilbabin** [comment]
Посібник буде правильніше. У польському перекладі, наприклад, взагалі підручник.

**Comment by ochkarik05** [comment]
@klymenkoo Ось ще приклади:

https://uk.glosbe.com/en/uk/tutorial

Як "Вступ" перекладається introduction. У вашій поточній редакції на tutorial в тексті вже посилаються саме як на посібник в декількох місцях.

**Comment by klymenkoo** [comment]
@ochkarik05 добре, звучить більш ніж переконливо :)
