### ISSUE TITLE
Термінологія: refs

### ISSUE THREAD

**Issue by klymenkoo** [reactjs/uk.reactjs.org#27]
На даний момент, згідно нашого [TRANSLATING.md](https://github.com/reactjs/uk.reactjs.org/blob/master/TRANSLATION.md), ми перекладаємо термін `refs` як `посилання`. 

Мені здається, що буде доцільніше перекладати цей термін як `рефи` для запобігання плутанини з звичайними посиланнями.

Хотілося б почути думки нашої спільноти з цього приводу 😀👇

**Comment by Kurzdor** [comment]
Краще всього залишити refs як рефи, тому що цей термін виключно пов'язаний з React і це не той термін, який треба перекладати на український варіант.

**Comment by mihilbabin** [comment]
+ за `рефи`, так як уже маємо `пропси`.
