### ISSUE TITLE
Термінологія: assert

### ISSUE THREAD

**Issue by Vanuan** [reactjs/uk.reactjs.org#32]
Обговорюємо переклад слова assert у значеннях "виклик функції перевірки результату теста" та власне твердження, що перевіряється цим тестом.

Української літератури на тему модульного тестування не знайшов.

Українська вікіпедія перекладає assert як припущення.
[https://uk.wikipedia.org/wiki/Припущення_(програмування)](https://uk.wikipedia.org/wiki/%D0%9F%D1%80%D0%B8%D0%BF%D1%83%D1%89%D0%B5%D0%BD%D0%BD%D1%8F_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F))

То може перекласти assert як "робити припущення"?' Або використати кальку з англійскої "асертувати"

Ось тут використовується дієслово "припускати" та фраза "перевірка тверджень":
https://refactoring.guru/uk/introduce-assertion

**Comment by mihilbabin** [comment]
Як на мене, `assert` - це не припущення, а `(с)твердження`.
Коли я пишу:
```
assert a == b
```
я стверджую, що `a` і `b` є рівними. Інакше - очікую, що програма згенерує виключення, або вийде з ненульовим статусом (у залежності від мови - наприклад, `AssertionError` в Python, вихід із програми в C/C++). Припущення може справдитись або ні. Твердження має справдитись у будь-якому випадку.
Але коли пишеться `it('should do things', ()=>{})`, то вже стає якось не дуже ствердно. `It` звичайно `should`, але не `must`... Я все рівно схиляюсь до `(с)твердження`, спробуйте мене переконати :smile:

**Comment by Vanuan** [comment]
Можливо, "очікування" або "пересвідчення" краще передають суть ассерту. Тобто коли я, як програміст пишу assert, я пересвідчуюсь у якомусь твердженні, я очікую, що моє передбачення/припущення справдиться.

Мені здається, що твердження більш підходить для перекладу слова "statement". А assert за своєю суттю є умовним викидуванням виключення. А виключення - це результат переходу в неочікуваний стан.

Тобто, якщо я очікую, що програма може згенерувати виключення, то це не твердження, це перевірка твердження, тобто це моє переконання, що воно має бути так. Тобто воно більш суб'єктивним. Слово "твердження" мені здається більш об'єктивним. Типу 2+2=4 - це твердження. Робити assert тут нема сенсу. А от "2*x = y" - це я вже не можу стверджувати, я повинен у цьому пересвідчитись.

**Comment by mihilbabin** [comment]
Якщо хочеться пересвідчитись, то можна ж просто написати `if`? :thinking:  Зазвичай, `assert` пишуть, коли знають, що тут має бути саме так, а не інакше. Якщо `assert` не справдився - це максимальний фейл. [Документація плюсів](http://www.cplusplus.com/reference/cassert/assert/), наприклад, явно визначає `assert`, як повний і безповоротний дроп процесу зі статусом `SIGABRT` і не дає відловити його через `catch`. У коді за посиланням вище - явний `assert(ptr != NULL)` викине на мороз кожного, хто передасть туди нульовий покажчик.
Дуже гарна відповідь на [SO](https://stackoverflow.com/questions/28973904/assert-in-try-catch-block). Кілька цитат, котрі певною мірою виражають мою думку:
> this should never happen here, if it happens there's a bug in my code, so I have to fix it

> The purpose of assert is the guarantee that the programmer doesn't make mistakes.

`Очікування` (expectation) не несе такого критичного відтінку.

Statement - це, як правило, оператор чи інструкція в коді.

**Comment by ApolllonDev** [comment]
> То може перекласти assert як "робити припущення"?' Або використати кальку з англійскої "асертувати"

Ми вже використовуємо `bundler` => `бандлер`, a також `hook` => `хук`.
Пропоную додати до словника `assert` => `асертувати`.
@klymenkoo, @mihilbabin, @Vanuan

**Comment by klymenkoo** [comment]
@ApolllonDev ми hook, refs, etc. перекладаємо як кальку з англійської, тому що ці терміни специфічні для React. А ось assert це поширений термін у тестуванні ПО.

**Comment by ApolllonDev** [comment]
> @ApolllonDev ми hook, refs, etc. перекладаємо як кальку з англійської, тому що ці терміни специфічні для React. А ось assert це поширений термін у тестуванні ПО.

Here is how they translated it on [Wiki](https://uk.wikipedia.org/wiki/%D0%9F%D1%80%D0%B8%D0%BF%D1%83%D1%89%D0%B5%D0%BD%D0%BD%D1%8F_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F)).

**Comment by ApolllonDev** [comment]
> Як на мене, `assert` - це не припущення, а `(с)твердження`.
> Коли я пишу:
> 
> ```
> assert a == b
> ```
> я стверджую, що `a` і `b` є рівними. Інакше - очікую, що програма згенерує виключення, або вийде з ненульовим статусом (у залежності від мови - наприклад, `AssertionError` в Python, вихід із програми в C/C++). Припущення може справдитись або ні. Твердження має справдитись у будь-якому випадку.
> Але коли пишеться `it('should do things', ()=>{})`, то вже стає якось не дуже ствердно. `It` звичайно `should`, але не `must`... Я все рівно схиляюсь до `(с)твердження`, спробуйте мене переконати 😄

So should I keep it as `стверджувати`?

> You can then begin to assert facts about the output.
> Потім ви можете почати стверджувати факти про формат виводу.

**Comment by klymenkoo** [comment]
Як на мене, я б обрав `припускати` для сумісності з Вікі.
