### ISSUE TITLE
Термінологія: callback ref

### ISSUE THREAD

**Issue by ApolllonDev** [reactjs/uk.reactjs.org#52]
> `callback ref` - `функціональний реф`, як варіант. Але таке має виноситись на голосування. @ApolllonDev, @klymenkoo FYI

> На даний момент, згідно нашого [TRANSLATING.md](https://github.com/reactjs/uk.reactjs.org/blob/master/TRANSLATION.md), ми перекладаємо термін `refs` як `посилання`.

> Хотілося б почути думки нашої спільноти з цього приводу 😀👇

**Comment by Kurzdor** [comment]
В TRANSLATING.md @klymenkoo оновив термін `refs` як `рефи`.
На жаль, MDN не надає українського варіанту, але якщо використовувати російский варіант `Функция обратного вызова` для callback [(Лінк)](https://developer.mozilla.org/ru/docs/%D0%A1%D0%BB%D0%BE%D0%B2%D0%B0%D1%80%D1%8C/%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D1%8F_%D0%BE%D0%B1%D1%80%D0%B0%D1%82%D0%BD%D0%BE%D0%B3%D0%BE_%D0%B2%D1%8B%D0%B7%D0%BE%D0%B2%D0%B0), то пропоную `реф зворотнього виклику`.

**Comment by klymenkoo** [comment]
Згідно [TRANSLATION.md](https://github.com/reactjs/uk.reactjs.org/blob/master/TRANSLATION.md), якщо поєднати `callback` & `ref`, то отримаємо `реф зворотнього виклику` 😀
