### ISSUE TITLE
Ukrainian Translation Final Steps!

### ISSUE THREAD

**Issue by tesseralis** [reactjs/uk.reactjs.org#67]
Congrats on almost finishing the Ukranian docs! There are just a couple more things we need to do before we can mark the core pages as complete!

* [x] Change the [DocSearch API key](https://github.com/reactjs/es.reactjs.org/blob/ed07fa53dc9ab7950e630900f7da3a7c821d63a6/src/components/LayoutHeader/DocSearch.js#L25)  #69 . One of the maintainers needs to [sign up for DocSearch](https://community.algolia.com/docsearch/#join-docsearch-program)
* [x] Go over the pages of the site one last time to check for consistency

**Comment by tesseralis** [comment]
Particular things I've noticed:

* The splash page isn't translated:

<img width="1280" alt="Screen Shot 2019-03-12 at 7 04 56 PM" src="https://user-images.githubusercontent.com/1278991/54248396-c25e0d80-44f9-11e9-834b-01a58b163424.png">

* The nav bar is cut off:

<img width="691" alt="Screen Shot 2019-03-12 at 7 05 25 PM" src="https://user-images.githubusercontent.com/1278991/54248419-d3a71a00-44f9-11e9-8c8b-be84b6a2bbb9.png">

The easiest way to fix this is to just decrease the width of the logo/home link:

<img width="677" alt="Screen Shot 2019-03-12 at 7 05 56 PM" src="https://user-images.githubusercontent.com/1278991/54248446-e3bef980-44f9-11e9-8cc9-211b5d9301ea.png">

**Comment by klymenkoo** [comment]
@tesseralis sounds good! Thank you, we'll work on it 🙌

**Comment by ApolllonDev** [comment]
@klymenkoo let's finish this one over the weekend.
`96% of core translation is completed` 🚀

**Comment by klymenkoo** [comment]
@ApolllonDev waiting for the last document: `Forms`.

**Comment by ApolllonDev** [comment]
#112 

> @ApolllonDev waiting for the last document: `Forms`.
