### ISSUE TITLE
Поверховий і Тестовий у нас вже перекладено як `рендер` у відповідних секціях by @ApolllonDev. Потрібно узгодити це.

### ISSUE THREAD

**Issue by ApolllonDev** [reactjs/uk.reactjs.org#78]
Поверховий і Тестовий у нас вже перекладено як `рендер` у відповідних секціях by @ApolllonDev. Потрібно узгодити це.

_Originally posted by @mihilbabin in https://github.com/reactjs/uk.reactjs.org/pull/71_

**Comment by ApolllonDev** [comment]
https://github.com/reactjs/uk.reactjs.org/pull/71#discussion_r266526717

**Comment by ApolllonDev** [comment]
@klymenkoo, @mihilbabin according to the [translation guide](https://github.com/reactjs/uk.reactjs.org/blob/master/TRANSLATION.md):

render(ing) | рендер, рендерити
-- | --
re-render(ing) | повторний рендер
render prop | рендер-проп
render props | рендер-пропси
rendered markup | відрендерена розмітка

**Comment by klymenkoo** [comment]
Render – рендер
Renderer – рендерер
